apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chroma-pvc
  labels:
    app: taxai
    component: chroma
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
