apiVersion: v1
kind: Secret
metadata:
  name: taxai-secret
type: Opaque
stringData:
  HUGGINGFACE_API_KEY: "your-huggingface-api-key"  # Replace with your actual API key
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
